apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: upkar/myapp:latest
        ports:
        - containerPort: 8080
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MESSAGE
